export const pins = [
  // {
  //   url: "https://code.xuyue.cc?query=30",
  //   description: "示例代码",
  // },
]

export const sites = [
  {
    url: import.meta.env.VITE_OJ,
    title: {
      "zh-Hans": "判题狗",
      "zh-Hant": "判題狗",
      en: "Judge Dog",
      ja: "判定犬",
      ko: "판정개",
      es: "Perro juez",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "在线判题网站",
      "zh-Hant": "在線判題網站",
      en: "Online judge platform",
      ja: "オンライン判定サイト",
      ko: "온라인 판정 사이트",
      es: "Plataforma de jueces en linea",
      meow: "喵喵喵喵喵喵",
    },
    icon: "noto--dog-face.svg",
  },
  {
    url: import.meta.env.VITE_CODE,
    title: {
      "zh-Hans": "自测猫",
      "zh-Hant": "自測貓",
      en: "Self Test Cat",
      ja: "自テスト猫",
      ko: "자가테스트猫",
      es: "Gato de autoevaluacion",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "代码运行网站",
      "zh-Hant": "代碼運行網站",
      en: "Code runner",
      ja: "コード実行サイト",
      ko: "코드 실행 사이트",
      es: "Sitio para ejecutar codigo",
      meow: "喵喵喵喵喵喵",
    },
    icon: "noto--cat-face.svg",
  },
  {
    url: import.meta.env.VITE_WEB,
    title: {
      "zh-Hans": "哈基米",
      "zh-Hant": "哈基米",
      en: "Hakimi",
      ja: "ハキミ",
      ko: "하키미",
      es: "Hakimi",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "Web 前端开发",
      "zh-Hant": "Web 前端開發",
      en: "Web frontend development",
      ja: "Webフロントエンド開発",
      ko: "웹 프론트엔드 개발",
      es: "Desarrollo frontend web",
      meow: "喵喵喵喵喵喵喵喵",
    },
    icon: "noto--honeybee.svg",
  },
  {
    url: import.meta.env.VITE_SHUATI,
    title: {
      "zh-Hans": "刷题鸭",
      "zh-Hant": "刷題鴨",
      en: "Practice Duck",
      ja: "演習アヒル",
      ko: "문제풀이오리",
      es: "Pato de practica",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "梁老师的刷题网站",
      "zh-Hant": "梁老師的刷題網站",
      en: "Practice problems by Mr. Liang",
      ja: "梁先生の演習サイト",
      ko: "량 선생님의 문제풀이 사이트",
      es: "Sitio de practicas del profe Liang",
      meow: "喵喵喵喵喵喵喵喵",
    },
    icon: "noto--paintbrush.svg",
  },
  {
    url: import.meta.env.VITE_BOOK,
    title: {
      "zh-Hans": "编程书",
      "zh-Hant": "編程書",
      en: "Coding Books",
      ja: "プログラミング書",
      ko: "프로그래밍 책",
      es: "Libros de programacion",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "编程和计算机相关知识汇总",
      "zh-Hant": "編程和計算機相關知識匯總",
      en: "CS knowledge summary",
      ja: "プログラミング/コンピュータ知識まとめ",
      ko: "프로그래밍/컴퓨터 지식 모음",
      es: "Resumen de conocimiento de programacion y computacion",
      meow: "喵喵喵喵喵喵喵喵喵喵喵喵",
    },
    icon: "noto--bookmark-tabs.svg",
  },
  {
    url: import.meta.env.VITE_BLOCKLY,
    title: {
      "zh-Hans": "小方块",
      "zh-Hant": "小方塊",
      en: "Little Blocks",
      ja: "小さなブロック",
      ko: "작은 블록",
      es: "Bloques pequenos",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "搭积木，学编程",
      "zh-Hant": "搭積木，學編程",
      en: "Learn coding with blocks",
      ja: "ブロックでプログラミング",
      ko: "블록으로 프로그래밍 배우기",
      es: "Aprende programacion con bloques",
      meow: "喵喵喵喵喵喵喵",
    },
    icon: "twemoji--brick.svg",
  },
  {
    url: import.meta.env.VITE_HUABU,
    title: {
      "zh-Hans": "白板",
      "zh-Hant": "白板",
      en: "Whiteboard",
      ja: "ホワイトボード",
      ko: "화이트보드",
      es: "Pizarra",
      meow: "喵喵",
    },
    description: {
      "zh-Hans": "在线板书",
      "zh-Hant": "在線板書",
      en: "Online whiteboard",
      ja: "オンライン板書",
      ko: "온라인 판서",
      es: "Pizarra en linea",
      meow: "喵喵喵喵",
    },
    icon: "noto--artist-palette.svg",
  },
  {
    url: import.meta.env.VITE_PPT,
    title: {
      "zh-Hans": "Python PPT",
      "zh-Hant": "Python PPT",
      en: "Python PPT",
      ja: "Python PPT",
      ko: "Python PPT",
      es: "Python PPT",
      meow: "喵喵喵喵喵喵",
    },
    description: {
      "zh-Hans": "Python 第一学期上课用",
      "zh-Hant": "Python 第一學期上課用",
      en: "Python semester 1 materials",
      ja: "Python 1学期授業用",
      ko: "Python 1학기 수업용",
      es: "Materiales de Python del primer semestre",
      meow: "喵喵喵喵喵喵喵喵喵喵喵喵喵喵",
    },
    icon: "material-icon-theme--python.svg",
  },
  {
    url: import.meta.env.VITE_PY,
    title: {
      "zh-Hans": "Python 项目",
      "zh-Hant": "Python 項目",
      en: "Python Projects",
      ja: "Python プロジェクト",
      ko: "Python 프로젝트",
      es: "Proyectos de Python",
      meow: "喵喵喵喵喵喵喵喵",
    },
    description: {
      "zh-Hans": "Python 第二学期上课用",
      "zh-Hant": "Python 第二學期上課用",
      en: "Python semester 2 materials",
      ja: "Python 2学期授業用",
      ko: "Python 2학기 수업용",
      es: "Materiales de Python del segundo semestre",
      meow: "喵喵喵喵喵喵喵",
    },
    icon: "material-icon-theme--folder-python-open.svg",
  },
].filter((site) => !!site.url)
