export const pins = [
  // {
  //   url: "https://code.xuyue.cc?query=30",
  //   description: "示例代码",
  // },
]

export const sites = [
  {
    url: import.meta.env.VITE_OJ,
    title: {
      "zh-Hans": "判题狗",
      wenyan: "判题犬",
      garbled: "è½◽",
      bin: "011",
      "zh-Hant": "判題狗",
      en: "Judge Dog",
      ja: "判定犬",
      ko: "판정개",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "在线判题网站",
      wenyan: "判题之所",
      garbled: "烫锟ä¢烫糊",
      bin: "010011",
      "zh-Hant": "在線判題網站",
      en: "Online judge platform",
      ja: "オンライン判定サイト",
      ko: "온라인 판정 사이트",
      meow: "喵喵喵喵喵喵",
    },
    icon: "noto--dog-face.svg",
  },
  {
    url: import.meta.env.VITE_CODE,
    title: {
      "zh-Hans": "自测猫",
      wenyan: "自试猫",
      garbled: "ä¢å",
      bin: "001",
      "zh-Hant": "自測貓",
      en: "Self Test Cat",
      ja: "自テスト猫",
      ko: "자가테스트猫",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "代码运行网站",
      wenyan: "行码之所",
      garbled: "¿屯屯糊¢◾",
      bin: "100011",
      "zh-Hant": "代碼運行網站",
      en: "Code runner",
      ja: "コード実行サイト",
      ko: "코드 실행 사이트",
      meow: "喵喵喵喵喵喵",
    },
    icon: "noto--cat-face.svg",
  },
  {
    url: import.meta.env.VITE_WEB,
    title: {
      "zh-Hans": "哈基米",
      wenyan: "哈基米",
      garbled: "¿▣▦",
      bin: "010",
      "zh-Hant": "哈基米",
      en: "Hakimi",
      ja: "ハキミ",
      ko: "하키미",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "Web 前端开发",
      wenyan: "网页前端之作",
      garbled: "ä▦▨斤¨è□¿",
      bin: "01111110",
      "zh-Hant": "Web 前端開發",
      en: "Web frontend development",
      ja: "Webフロントエンド開発",
      ko: "웹 프론트엔드 개발",
      meow: "喵喵喵喵喵喵喵喵",
    },
    icon: "noto--honeybee.svg",
  },
  {
    url: import.meta.env.VITE_SHUATI,
    title: {
      "zh-Hans": "刷题鸭",
      wenyan: "习题鸭",
      garbled: "¿æä",
      bin: "110",
      "zh-Hant": "刷題鴨",
      en: "Practice Duck",
      ja: "演習アヒル",
      ko: "문제풀이오리",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "梁老师的刷题网站",
      wenyan: "梁师习题之所",
      garbled: "糊¿拷èç¿□¨",
      bin: "00011101",
      "zh-Hant": "梁老師的刷題網站",
      en: "Practice problems by Mr. Liang",
      ja: "梁先生の演習サイト",
      ko: "량 선생님의 문제풀이 사이트",
      meow: "喵喵喵喵喵喵喵喵",
    },
    icon: "noto--paintbrush.svg",
  },
  {
    url: import.meta.env.VITE_BOOK,
    title: {
      "zh-Hans": "编程书",
      wenyan: "程式书",
      garbled: "¬拷拷",
      bin: "000",
      "zh-Hant": "編程書",
      en: "Coding Books",
      ja: "プログラミング書",
      ko: "프로그래밍 책",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "编程和计算机相关知识汇总",
      wenyan: "程式及计算机知识总览",
      garbled: "拷¨锟斤锟¬锟¬ä▧斤¨",
      bin: "100101111000",
      "zh-Hant": "編程和計算機相關知識匯總",
      en: "CS knowledge summary",
      ja: "プログラミング/コンピュータ知識まとめ",
      ko: "프로그래밍/컴퓨터 지식 모음",
      meow: "喵喵喵喵喵喵喵喵喵喵喵喵",
    },
    icon: "noto--bookmark-tabs.svg",
  },
  {
    url: import.meta.env.VITE_BLOCKLY,
    title: {
      "zh-Hans": "小方块",
      wenyan: "小方块",
      garbled: "¨糊",
      bin: "110",
      "zh-Hant": "小方塊",
      en: "Little Blocks",
      ja: "小さなブロック",
      ko: "작은 블록",
      meow: "喵喵喵",
    },
    description: {
      "zh-Hans": "搭积木，学编程",
      wenyan: "以积木习程式",
      garbled: "◽¬拷ç¿斤锟",
      bin: "1101101",
      "zh-Hant": "搭積木，學編程",
      en: "Learn coding with blocks",
      ja: "ブロックでプログラミング",
      ko: "블록으로 프로그래밍 배우기",
      meow: "喵喵喵喵喵喵喵",
    },
    icon: "twemoji--brick.svg",
  },
  {
    url: import.meta.env.VITE_HUABU,
    title: {
      "zh-Hans": "白板",
      wenyan: "白板",
      garbled: "¿拷",
      bin: "01",
      "zh-Hant": "白板",
      en: "Whiteboard",
      ja: "ホワイトボード",
      ko: "화이트보드",
      meow: "喵喵",
    },
    description: {
      "zh-Hans": "在线板书",
      wenyan: "线上板书",
      garbled: "¬¿■¿",
      bin: "0001",
      "zh-Hant": "在線板書",
      en: "Online whiteboard",
      ja: "オンライン板書",
      ko: "온라인 판서",
      meow: "喵喵喵喵",
    },
    icon: "noto--artist-palette.svg",
  },
  {
    url: import.meta.env.VITE_PPT,
    title: {
      "zh-Hans": "Python PPT",
      wenyan: "蟒语课札",
      garbled: "锟¢¥烫拷□锟▧▢è",
      bin: "1001011111",
      "zh-Hant": "Python PPT",
      en: "Python PPT",
      ja: "Python PPT",
      ko: "Python PPT",
      meow: "喵喵喵喵喵喵",
    },
    description: {
      "zh-Hans": "Python 第一学期上课用",
      wenyan: "蟒语首学期课用",
      garbled: "糊èå▢噪□¬▦◽烫拷ä¬",
      bin: "00000010111011",
      "zh-Hant": "Python 第一學期上課用",
      en: "Python semester 1 materials",
      ja: "Python 1学期授業用",
      ko: "Python 1학기 수업용",
      meow: "喵喵喵喵喵喵喵喵喵喵喵喵喵喵",
    },
    icon: "material-icon-theme--python.svg",
  },
  {
    url: import.meta.env.VITE_PY,
    title: {
      "zh-Hans": "Python 项目",
      wenyan: "蟒语诸业",
      garbled: "▧ç¬ä▧◾斤糊",
      bin: "101110111",
      "zh-Hant": "Python 項目",
      en: "Python Projects",
      ja: "Python プロジェクト",
      ko: "Python 프로젝트",
      meow: "喵喵喵喵喵喵喵喵",
    },
    description: {
      "zh-Hans": "Python 第二学期上课用",
      wenyan: "蟒语次学期课用",
      garbled: "屯▤½¨ååç锟■噪屯屯◼¿",
      bin: "11110110110010",
      "zh-Hant": "Python 第二學期上課用",
      en: "Python semester 2 materials",
      ja: "Python 2学期授業用",
      ko: "Python 2학기 수업용",
      meow: "喵喵喵喵喵喵喵",
    },
    icon: "material-icon-theme--folder-python-open.svg",
  },
].filter((site) => !!site.url)
